-- Create Table Queries for BANK_DB

-- ACCOUNT_INFO Table
CREATE TABLE IF NOT EXISTS ACCOUNT_INFO (
    ACCOUNT_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    IFSC_CODE VARCHAR(10),
    ACCOUNT_TYPE VARCHAR(50),
    INITIAL_DEPOSIT DECIMAL(10, 2),
    INTEREST DECIMAL(4, 2),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID),
    FOREIGN KEY (IFSC_CODE) REFERENCES BANK_INFO(IFSC_CODE)
);

-- BANK_INFO Table
CREATE TABLE IF NOT EXISTS BANK_INFO (
    IFSC_CODE VARCHAR(10) PRIMARY KEY,
    BRANCH_NAME VARCHAR(255),
    LOCATION VARCHAR(255)
);

-- CUSTOMER_PERSONAL_INFO Table
CREATE TABLE IF NOT EXISTS CUSTOMER_PERSONAL_INFO (
    CUSTOMER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    DATE_OF_BIRTH DATE,
    ADDRESS VARCHAR(255),
    CONTACT_NUMBER VARCHAR(15)
);

-- CUSTOMER_REFERENCE_INFO Table
CREATE TABLE IF NOT EXISTS CUSTOMER_REFERENCE_INFO (
    CUSTOMER_ID INT,
    RELATION VARCHAR(50),
    REFERENCE_ACC_NAME VARCHAR(255),
    PRIMARY KEY (CUSTOMER_ID, RELATION),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
);
